<?php
/**
 * Flickr Widget
 *
 * @package Smart Blog
 * @since 1.0
 */

add_action( 'widgets_init', 'themepixels_register_widget_flickr' );
function themepixels_register_widget_flickr() {
	register_widget( 'themepixels_widget_flickr' );
}

class themepixels_widget_flickr extends WP_Widget {

	public function __construct() {
		$widget_ops = array( 'classname' => 'flickr_widget', 'description' => __( 'Display your flickr photos', 'themepixels' ) );
		parent::__construct( 'themepixels_flickr', __( 'Themepixels - Flickr', 'themepixels' ), $widget_ops );
	}

	public function widget( $args, $instance ) {
		extract($args);
		$title = apply_filters('widget_title', $instance['title']);
		$flickr_id = $instance['flickr_id'];
		$flickr_api = $instance['flickr_api'];
		$count = intval( $instance['count'] );
		$sort = $instance['sort'];
		$enable_lightbox = isset( $instance['enable_lightbox'] ) ? true : false;

		echo $before_widget;
		if( $title ) {
			echo $before_title . $title . $after_title;
		} ?>

		<div class="flickr-widget-wrapper clearfix">
			<?php if( $flickr_id && $flickr_api ) { ?>
				<script type="text/javascript">
					function jsonFlickrApi(rsp) {
						if (rsp.stat != "ok"){
							// If this executes, something broke!
							return;
						}

						//variable "s" is going to contain
						//all the markup that is generated by the loop below
						 var s = "";

						//this loop runs through every item and creates HTML
						for (var i=0; i < rsp.photos.photo.length; i++) {
							photo = rsp.photos.photo[ i ];

							//notice that "t.jpg" is where you change the
							//size of the image
							t_url = "http://farm" + photo.farm +
							".static.flickr.com/" + photo.server + "/" +
							photo.id + "_" + photo.secret + "_" + "s.jpg";

							full_img_url = "http://farm" + photo.farm +
							".static.flickr.com/" + photo.server + "/" +
							photo.id + "_" + photo.secret + "_" + "z.jpg";

							p_url = "http://www.flickr.com/photos/" +
							photo.owner + "/" + photo.id;

							<?php if( $enable_lightbox == true ) { ?>
								s += '<div class="flickr-badge-image gallery-lightbox"><a href="' + full_img_url + '">' + '<img alt="'+
								photo.title + '"src="' + t_url + '"/>' + '</a></div>';
							<?php } else { ?>
								s += '<div class="flickr-badge-image"><a href="' + p_url + '">' + '<img alt="'+
								photo.title + '"src="' + t_url + '"/>' + '</a></div>';
							<?php } ?>
						}
						 
						document.writeln(s);
						//this tells the JavaScript to write
						//everything in variable "s" onto the page
					}
				</script>
				<script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;user_id=<?php echo esc_js( $flickr_id ); ?>&amp;sort=<?php echo esc_js( $sort ); ?>&amp;media=photos&amp;privacy_filter=1&amp;per_page=<?php echo intval( $count ); ?>&amp;api_key=<?php echo esc_js( $flickr_api ); ?>"></script>
				<script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;group_id=<?php echo esc_js( $flickr_id ); ?>&amp;sort=<?php echo esc_js( $sort ); ?>&amp;media=photos&amp;privacy_filter=1&amp;per_page=<?php echo intval( $count ); ?>&amp;api_key=<?php echo esc_js( $flickr_api ); ?>"></script>
			<?php } ?>
		</div>

		<?php
		echo $after_widget;
	}

	public function update( $new_instance, $old_instance ) {
		$instance = $old_instance;

		$instance['title'] = strip_tags($new_instance['title']);
		$instance['flickr_id'] = $new_instance['flickr_id'];
		$instance['flickr_api'] = $new_instance['flickr_api'];
		$instance['count'] = $new_instance['count'];
		$instance['sort'] = $new_instance['sort'];
		$instance['enable_lightbox'] = $new_instance['enable_lightbox'];

		return $instance;
	}

	public function form( $instance ) {
		$defaults =  array(
			'title'				=> '',
			'flickr_id'			=> '',
			'flickr_api'		=> '',
			'count'				=> '9',
			'sort'				=> 'date-posted-desc',
			'enable_lightbox'	=> 'on'
		);

		$instance = wp_parse_args( (array) $instance, $defaults ); ?>

		<p>
			<label for="<?php echo $this->get_field_id('title'); ?>"><?php _e( 'Title:', 'themepixels' ); ?></label>
			<input class="widefat" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" type="text" value="<?php echo esc_attr( $instance['title'] ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id('flickr_id'); ?>"><?php _e( 'Flickr ID: ', 'themepixels' ); ?>
				<small><a href="<?php echo esc_url( 'http://idgettr.com/' ); ?>" target="_blank"><?php _e('To get your ID', 'themepixels'); ?></a></small>
			</label>
			<input class="widefat" id="<?php echo $this->get_field_id('flickr_id'); ?>" name="<?php echo $this->get_field_name('flickr_id'); ?>" type="text" value="<?php echo esc_attr( $instance['flickr_id'] ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id('flickr_api'); ?>"><?php _e( 'Flickr API: ', 'themepixels' ); ?>
				<small><a href="<?php echo esc_url( 'https://www.flickr.com/services/apps/create/apply' ); ?>" target="_blank"><?php _e('To get your API', 'themepixels'); ?></a></small>
			</label>
			<input class="widefat" id="<?php echo $this->get_field_id('flickr_api'); ?>" name="<?php echo $this->get_field_name('flickr_api'); ?>" type="text" value="<?php echo esc_attr( $instance['flickr_api'] ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id('count'); ?>"><?php _e( 'Number of images to show:', 'themepixels' ); ?></label>
			<input class="widefat" id="<?php echo $this->get_field_id('count'); ?>" name="<?php echo $this->get_field_name('count'); ?>" type="text" value="<?php echo intval( $instance['count'] ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id('sort'); ?>"><?php _e( 'Sort by:', 'themepixels' ); ?></label>
			<select name="<?php echo $this->get_field_name('sort'); ?>" id="<?php echo $this->get_field_id('sort'); ?>" class="widefat">
				<option value="date-posted-desc"<?php selected( $instance['sort'], 'date-posted-desc' ); ?>><?php _e( 'By date uploaded (Newest first)', 'themepixels' ); ?></option>
				<option value="date-posted-asc"<?php selected( $instance['sort'], 'date-posted-asc' ); ?>><?php _e( 'By date uploaded (Oldest first)', 'themepixels' ); ?></option>
				<option value="date-taken-desc"<?php selected( $instance['sort'], 'date-taken-desc' ); ?>><?php _e( 'By date taken (Newest first)', 'themepixels' ); ?></option>
				<option value="date-taken-asc"<?php selected( $instance['sort'], 'date-taken-asc' ); ?>><?php _e( 'By date taken (Oldest first)', 'themepixels' ); ?></option>
				<option value="interestingness-desc"<?php selected( $instance['sort'], 'interestingness-desc' ); ?>><?php _e( 'By Views (Highest first)', 'themepixels' ); ?></option>
				<option value="interestingness-asc"<?php selected( $instance['sort'], 'interestingness-asc' ); ?>><?php _e( 'By Views (Lowest first)', 'themepixels' ); ?></option>
			</select>
		</p>
		<p>
			<input type="checkbox" class="checkbox" id="<?php echo $this->get_field_id('enable_lightbox'); ?>" name="<?php echo $this->get_field_name('enable_lightbox'); ?>"<?php checked( $instance['enable_lightbox'], 'on' ); ?> />
			<label for="<?php echo $this->get_field_id('enable_lightbox'); ?>"><?php _e( 'Enable Lightbox', 'themepixels' ); ?></label>
		</p>
	<?php
	}
}